### PR TITLE
Implement Database Schema for Assignment Management

### PR DESCRIPTION
**Pull request by jlgsl**
Define the assignment schema including necessary fields such as title, description, dueDate, and teacherId.
 Set up the MongoDB collection for assignments within our current database environment.
 Ensure the schema supports references or embedded documents for future features like questions and submissions.
 Implement model validations to ensure data integrity when assignments are created or updated.
 Develop basic CRUD operations for assignments in the backend, including API endpoints for creating, reading, updating, and deleting assignments.

### CODE REVIEW

**Review by itsdylantan — APPROVED** [review]

**Review by Samarth-G — CHANGES_REQUESTED** [review]
I just merged my branch that had courseModel.js, courseController.js and courseRoutes.js 
I think you can remove courseModel from this pull request, and instead merge it first and then add assignments to courseModel.js

**Comment by jlgsl** [comment]
courseModel.js removed

**Comment by jlgsl** [comment]
> I just merged my branch that had courseModel.js, courseController.js and courseRoutes.js I think you can remove courseModel from this pull request, and instead merge it first and resolve the conflicting files, then later add assignments to courseModel.js

courseModel.js removed

**Review by lilyy1 — CHANGES_REQUESTED** [review]
lgtm, i think you just have 1 small merge conflict in app.js with the spacing, once you fix that i think it's good

**Pull request closed without merging**
