### PR TITLE
Courses Page Basic

### PR DESCRIPTION
**Pull request by jlgsl**

### CODE REVIEW

**Review by Samarth-G — APPROVED** [review]
Looks good!

**Review by lilyy1 — CHANGES_REQUESTED** [review]
your code looks good, I just wanted to check if you meant to push an empty art.html, computer-science.html, and english.html file? Also can you add comments in the code giving credit to where you got the images from(whether or not you got it from somewhere online or had ai generate it)?

**Comment by itsdylantan** [comment]
Looks good but we might have to take a look if it conflicts with the create-courses page that I am currently working on

**Review by itsdylantan — APPROVED** [review]
Looks good, I am currently working on the creating courses page. Doesn't look like there are any conflicts

**Pull request merged**
